import numpy as np

# Reads the data from saved text files generated by the simulator
# Returns
# - steps   step number
# - t       time 
# - g       gravitional acceleration (scalar)
# - x       positions at cell cetners (array)
# - b       elevation of the bottom   (array)
# - s       elevation of the surface  (array)
# - u       water flow velocity       (array)
def read_data(filename):
    # read header
    fin = open(filename, 'r')
    
    line = fin.readline()
    words = line.split()
    steps = int(words[3])
    
    line = fin.readline()
    words = line.split()
    t = float(words[3])
    
    line = fin.readline()
    words = line.split()
    g = float(words[3])
    
    fin.close()
    
    # read data
    data = np.genfromtxt(filename, skip_header = 3)
    
    x = data[:,0]
    b = data[:,1]
    s = data[:,2]
    u = data[:,3]
    
    return steps, t, g, x, b, s, u